### PR TITLE
Drop setting HSTS header

### PR DESCRIPTION
**Pull request by arothuis**
This should be configured on the server level in production, see OpenConext-Deploy

#54

### CODE REVIEW

**Comment by thijskh** [comment]
:+1:

**Comment by thijskh** [comment]
:+1:

**Comment by thijskh** [comment]
As long as this doesn't break running Profile behind a load balancer where Profile itself is accessed over http from the frontend.

**Comment by arothuis** [comment]
According to the [NelmioSecurityBundle documentation](https://github.com/nelmio/NelmioSecurityBundle#forced-httpsssl-handling), it will "redirect all users reaching the site with a http:// URL to a https:// URL". So if you cannot deal with `https://profile.*`, this will not work.

I think you could also enforce "force_ssl" using webserver configuration, for instance by using rewrite rules. If we do not want to require the application-level "enforcement" of SSL, we could drop this configuration.

**Comment by thijskh** [comment]
Enabling it doesn't seem to cause trouble in our test environment. So :+1: from me.

**Comment by arothuis** [comment]
Thanks for testing it!

**Pull request merged**
