### PR TITLE
Add HTTPS to development VM

### PR DESCRIPTION
**Pull request by arothuis**
The webserver has to be configured properly in order for HTTPS to work.

Part of [Ticket 106202952](https://www.pivotaltracker.com/story/show/106202952)

### CODE REVIEW

**Comment by arothuis** [comment]
@rjkip, @DRvanR

**Comment by rjkip** [comment]
Looks about right :+1:

**Comment by DRvanR** [comment]
:+1:

**Comment by arothuis** [comment]
@DRvanR, @rjkip; 
After a full vagrant destroy + up, found out nginx was misconfigured.

**Comment by rjkip** [comment]
It is actually the semicolon that is missing here. But Nginx recommends `listen 443 ssl;`, so :+1: regardless.

**Comment by DRvanR** [comment]
:+1:

**Pull request merged**
